services:
  daedalus_bot:
    build: 
      context: .
      dockerfile: DaedalusBot/Dockerfile
    ports:
      - "5001:5001"
    networks:
      - daedalus-network  
    env_file: ".env"
  
  daedalus_search:
    build: 
      context: .
      dockerfile: DaedalusSearch/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    networks:
      - daedalus-network
    env_file: ".env"

networks:
  daedalus-network:
    driver: bridge

